### PR TITLE
Better document obtaining and using macOS drivers

### PR DESCRIPTION
**Pull request by davidfokkema**
Changes proposed in this pull request:

* Create a conda environment
* Copy the drivers and fix a broken library link

Until such time as the drivers being available as a separate download for macOS, I think this is by far the best method to install and use the drivers. I tried the forum post, but I still needed to google around and do some work to fix things.

### CODE REVIEW

**Comment by neil-hamilton** [comment]
We don't accept pull requests for our repositories.  Please contact support@picotech.com if there is a issue with the repository.

**Comment by davidfokkema** [comment]
Is this a change in policy? #8 was previously accepted. This is a pity. As for this pull request: the current description for using the libraries on MacOS are incomplete, IMHO. I don't know if mailing support will help since I solved this problem. Is there a specific reason for not accepting pull requests?

**Comment by neil-hamilton** [comment]
This is policy change as we no longer have the resources available to code review, test and do document reviews to the level needed for us to accept changes from members of the public made to our public code repositories and public facing documents.

**Comment by davidfokkema** [comment]
That’s a pity, but I understand. Good luck!

**Pull request closed without merging**
