### PR TITLE
Fix typo in PICO_PORT_DIGITAL_CHANNEL enum

### PR DESCRIPTION
**Pull request by wsxrdv**
A missing comma in the list caused the strings
PICO_PORT_DIGITAL_CHANNEL4 and PICO_PORT_DIGITAL_CHANNEL5 to be merged. Resulting in the enum not working properly.

Fixes #.

Changes proposed in this pull request:

* Add a missing comma and thus fix an enum.

### CODE REVIEW

**Comment by wsxrdv** [comment]
@neil-hamilton PTAL

**Comment by wsxrdv** [comment]
@davidfokkema PTAL

**Comment by davidfokkema** [comment]
LGTM, but not sure why you tagged me. I'm not a PicoTech employee and don't have permission to merge pull requests, sorry!

**Comment by davidfokkema** [comment]
> Sorry to bother you. Do you know anyone who has permission to merge PRs?

No problem, I was just a bit surprised. It seems that @neil-hamilton has been the only one working on this code the last few years. He's probably also required to work on other projects, and at some point (some years back) company policy changed and they stopped accepting issues and PRs from the community. This is only fixing a typo so it may be merged, but it's taking quite some time...

**Pull request merged**
